version: '3.8'

services:
  eurekaserver:
    build:
      context: ../Eureka
      dockerfile: Dockerfile
    image: sandrocordova/udemy-microservicios:eureka
    ports:
    - "8090:8090"
    mem_limit: 1500m
    cpus: "2.0"
    networks:
      - practica
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s
      
  configserver:
    build:
      context: ../configuracion
      dockerfile: Dockerfile
    image: sandrocordova/udemy-microservicios:configserve
    ports:
      - "8080:8080"
    mem_limit: 1500m
    cpus: "2.0"
    networks:
      - practica
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: git
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/sandrocordova99/Udemy-configservems-practica.git
      SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START: "true"
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: config
      SPRING_CLOUD_CONFIG_SERVER_GIT_TIMEOUT: "10"

      #EUREKA
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8090/eureka/
      EUREKA_INSTANCE_HOSTNAME: configserver # ¡Esta es la línea clave!
      # ACTUATOR CONFIG - AÑADIDO

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s 

  mysql-db-cliente1:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql 
      MYSQL_DATABASE: practica_db_cliente1
    mem_limit: 1500m
    cpus: "2.0"
    volumes:
      - volumes_data_cliente1:/var/lib/mysql
    networks:
      - practica
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  cliente1:
    build:
      context: ../Cliente1
      dockerfile: Dockerfile
    image: sandrocordova/udemy-microservicios:cliente1
    ports:
      - "8081:8081"
    mem_limit: 1500m
    cpus: "2.0"
    networks:
      - practica
    depends_on:
      configserver:
        condition: service_healthy
      mysql-db-cliente1:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    volumes:
      - ../Cliente1/src:/app/src
      - ../Cliente1/pom.xml:/app/pom.xml
    command: mvn spring-boot:run -Dspring.jpa.hibernate.ddl-auto=update
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-cliente1:3306/practica_db_cliente1?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      
      # CONFIGURACIÓN EUREKA PARA QUE FUNCIONE EL LINK
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8090/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      #No entiendo esto -> 
      EUREKA_INSTANCE_HOSTNAME: cliente1 
      EUREKA_INSTANCE_INSTANCE_ID: cliente1:localhost:8081
      
      # ACTUATOR CONFIG
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"

  mysql-db-producto:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql 
      MYSQL_DATABASE: practica_db_productos
    mem_limit: 1500m
    cpus: "2.0"
    volumes:
      - volumes_data_producto:/var/lib/mysql
    networks:
      - practica
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  productos:
    build:
      context: ../Productos
      dockerfile: Dockerfile
    image: sandrocordova/udemy-microservicios:productos
    ports:
      - "8082:8082"
    mem_limit: 1500m
    cpus: "2.0"
    networks:
      - practica
    depends_on:
      configserver:
        condition: service_healthy
      mysql-db-producto:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    volumes:
      - ../Productos/src:/app/src
      - ../Productos/pom.xml:/app/pom.xml
    command: mvn spring-boot:run -Dspring.jpa.hibernate.ddl-auto=update
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db-producto:3306/practica_db_productos?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8090/eureka/
      # CONFIGURACIÓN EUREKA PARA QUE FUNCIONE EL LINK
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_HOSTNAME: productos
      EUREKA_INSTANCE_INSTANCE_ID: productos:localhost:8082
      # ACTUATOR CONFIG
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_ENDPOINT_INFO_ENABLED: "true"

networks:
  practica: 
    driver: bridge
volumes:
  volumes_data_cliente1:
  volumes_data_producto: